issues:
  exclude-files:
    - "(.+)_test.go"

linters:
  disable-all: true
  enable:
    - durationcheck
    - errcheck
    - forcetypeassert
    - gosec
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
    - govet
