version: "2"

linters:
  enable:
    - durationcheck
    - errcheck
    - forcetypeassert
    - gosec
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
    - govet
