version: "2"

linters:
  default: none
  enable:
    - durationcheck
    - errcheck
    - errorlint
    - forcetypeassert
    - gosec
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nestif
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
    - govet
  settings:
    errorlint:
      errorf: true
      asserts: true
      comparison: true
