issues:
  exclude-files:
    - (.+)_test.go
    - internal/testing

run:
  skip-dirs:
    - vendor

linters:
  disable-all: true
  enable:
    - durationcheck
    - errcheck
    - forcetypeassert
    - gosec
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
    - govet
