version: "2"

issues:
  max-per-linter: 0
  max-same-issues: 0
  exclude-files:
    - (.+)_test.go
    - internal/testing

linters:
  disable-all: true
  enable:
    - durationcheck
    - errcheck
    - forcetypeassert
    - gosec
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
    - govet
