issues:
  max-per-linter: 0
  max-same-issues: 0

run:
  skip-files:
    - (.+)_test.go
    - internal/testing

linters:
  disable-all: true
  enable:
    - durationcheck
    - errcheck
    - exportloopref
    - forcetypeassert
    - godot
    - gofmt
    - gosimple
    - gosec
    - ineffassign
    - makezero
    - goimports
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - tenv
    - unconvert
    - unparam
    - unused
    - vet
