auth_token               = "my-secret-key"
organization_id          = "<organization_id>"
project_id               = "b9b467e2-cca0-4fc7-ab54-3cc2faba51c9"
host                     = "https://cloudapi.cloud.couchbase.com"
database_credential_name = "test_db_user"
cluster_id               = "546caf5b-f495-45fc-93e5-7a40e0ee2a17"
password                 = "Secret12$#"
