auth_token               = "<v4-api-key-secret>"
organization_id          = "<organization_id>"
project_id               = "<project_id>"
host                     = "https://cloudapi.cloud.couchbase.com"
database_credential_name = "test_db_user"
cluster_id               = "546caf5b-f495-45fc-93e5-7a40e0ee2a17"
password                 = "Secret12$#"
