provider:
  name: couchbase_capella

resources:
  project:
    create:
      path: /v4/organizations/{organizationId}/projects
      method: POST
    read:
      path: /v4/organizations/{organizationId}/projects/{projectId}
      method: GET
    update:
      path: /v4/organizations/{organizationId}/projects/{projectId}
      method: PUT
    delete:
      path: /v4/organizations/{organizationId}/projects/{projectId}
      method: DELETE
    schema:
      attributes:
        id:
          description: The GUID4 ID of the project.
          type: string
          computed: true
        organization_id:
          description: The GUID4 ID of the organization.
          type: string
          required: true
        name:
          description: The name of the project.
          type: string
          required: true
        description:
          description: A short description of the project (up to 256 characters).
          type: string
          optional: true
        etag:
          description: ETag header value returned by the server.
          type: string
          computed: true

data_sources:
  projects:
    read:
      path: /v4/organizations/{organizationId}/projects
      method: GET
    schema:
      attributes:
        organization_id:
          description: The GUID4 ID of the organization.
          type: string
          required: true
        data:
          description: List of projects.
          type: list(object)
          computed: true
          object:
            attributes:
              id:
                type: string
                computed: true
              organization_id:
                type: string
                computed: true
              name:
                type: string
                computed: true
              description:
                type: string
                computed: true
              etag:
                type: string
                computed: true

