name: Acceptance Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      TF_VAR_auth_token: ${{ secrets.CAPELLA_AUTH_TOKEN }}
      TF_VAR_organization_id: ${{ secrets.CAPELLA_ORGANIZATION_ID }}
      TF_VAR_host: ${{ secrets.CAPELLA_HOST }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4 # this action has caching built in
        with:
          go-version-file: 'go.mod'
          cache: false
        id: go
      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: cache-${{ github.run_id }}
      - name: Run acceptance tests
        run: make testacc
