name: Acceptance Tests
concurrency:
  group: acceptance-tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'Makefile'
      - 'docs/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      TF_VAR_auth_token: ${{ secrets.CAPELLA_AUTH_TOKEN }}
      TF_VAR_organization_id: ${{ secrets.CAPELLA_ORGANIZATION_ID }}
      TF_VAR_host: ${{ secrets.CAPELLA_HOST }}

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
        id: go
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum') }}
      - name: Run acceptance tests
        run: make testacc
