name: "Label PR Based on Template"

on:
  pull_request:

jobs:
  label-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: read

    steps:
      - name: Check PR body
        id: check-pr
        run: |
          if [ -z "${{ github.event.pull_request.body }}" ]; then
            echo "PR body is empty. Please fill out the PR template."
            exit 1
          fi

      - name: Extract and set labels based on PR body
        id: get-labels
        run: |
          echo "PR_BODY<<EOF" >> $GITHUB_ENV
          echo "${{ github.event.pull_request.body }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Determine which labels to apply
        id: determine-labels
        run: |
          declare -a LABELS=()
          
          # Core changes
          if echo "${{ env.PR_BODY }}" | grep -q '\[X\].*Bug fix (non-breaking change which fixes an issue)'; then
            LABELS+=("bug")
          fi
          if echo "${{ env.PR_BODY }}" | grep -q '\[X\].*New feature (non-breaking change which adds functionality)'; then
            LABELS+=("enhancement")
          fi
          if echo "${{ env.PR_BODY }}" | grep -q '\[X\].*Breaking change'; then
            LABELS+=("breaking change")
          fi
          
          # Documentation
          if echo "${{ env.PR_BODY }}" | grep -q '\[X\].*Documentation fix/enhancement'; then
            LABELS+=("documentation")
          fi
          
          # Output the labels
          if [ ${#LABELS[@]} -eq 0 ]; then
            echo "labels=needs-triage" >> $GITHUB_OUTPUT
          else
            # Join array elements with comma
            IFS=,
            echo "labels=${LABELS[*]}" >> $GITHUB_OUTPUT
          fi
          
          # Debug output
          echo "Detected labels: ${LABELS[*]}"

      - name: Add labels
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labels = '${{ steps.determine-labels.outputs.labels }}'.split(',');
            console.log('Adding labels:', labels);
            
            try {
              await github.rest.issues.addLabels({
                ...context.repo,
                issue_number: context.payload.pull_request.number,
                labels: labels
              });
              console.log('Successfully added labels');
            } catch (error) {
              console.log('Error adding labels:', error);
              throw error;
            }

      - name: Add comment if no template matches found
        if: steps.determine-labels.outputs.labels == 'needs-triage'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: prNumber,
              body: 'No PR template selections were detected. Please make sure to fill out the PR template properly by selecting the appropriate checkboxes.'
            });