name: PR Description Check

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  check-pr-description:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Description
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Fetch the current PR data
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            const description = pr.data.body || '';
            const defaultText = "Please include a summary of the fix/feature/change, including any relevant motivation and context.";
            
            // Check if description is default or empty
            if (!description || description.trim() === '' || description.includes(defaultText)) {
              const errorMessage = `📝 PR Description Error:
                Your PR description needs attention.
                
                Description Requirements:
                - Must not be empty
                - Must not contain only the default template text
                - Should include:
                  * A clear summary of the changes
                  * Motivation for the changes
                  * Any relevant context
                
                Please replace the default text with a meaningful description of your changes.`;
              
              // Add comment to the PR
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: errorMessage
              });
              
              core.setFailed('PR description validation failed. Please check the comment for details.');
            }
